-- Create article
CREATE TABLE article ( word_count VARCHAR(50), 
Snippet TEXT,
web_url VARCHAR(255), 
print_section VARCHAR(255), 
uri VARCHAR(255), 
section_id BIGINT, 
article_id BIGINT, 
source VARCHAR(255), 
document_type VARCHAR(50), 
type_of_material VARCHAR(255), 
lead_paragraph TEXT, 
pub_date VARCHAR(50),
abstract TEXT, 
_id VARCHAR(255),
 print_page VARCHAR(50),
PRIMARY KEY (article_id)
);

-- Create section
CREATE TABLE section (
    section_name VARCHAR(255),
    subsection_name VARCHAR(255),
    news_desk VARCHAR(255),
    section_id BIGINT,
    PRIMARY KEY (section_id)
);

ALTER TABLE article ADD CONSTRAINT fk_section_id FOREIGN KEY (section_id) REFERENCES section(section_id);

-- Import the CSV generated by Glue
mysqlimport   --fields-terminated-by=, --local -u root  -p  nyt article.csv --fields-optionally-enclosed-by='"'

-- Remove empty rows
delete from article where _id = '';
delete from section where section_name = '' and news_desk = '' and subsection_name = '';
delete from article where lead_paragraph = 'lead_paragraph' and web_url='web_url';

-- Fix errors
ALTER TABLE article RENAME COLUMN snippet TO temp_snippet;
ALTER TABLE article RENAME COLUMN word_count TO snippet;
ALTER TABLE article RENAME COLUMN temp_snippet TO word_count;

-- word_count to INT
ALTER TABLE article ADD COLUMN word_count_temp INT;
UPDATE article SET word_count_temp = CAST(TRIM(TRAILING '.0' FROM word_count) AS DECIMAL(10,0));
ALTER TABLE article DROP COLUMN word_count;
ALTER TABLE article CHANGE COLUMN word_count_temp word_count INT;

-- pub_date STRING to DATE
ALTER TABLE article ADD COLUMN pub_date_temp VARCHAR(25);
UPDATE article SET pub_date_temp = LEFT(pub_date, 19);  -- Extract the first 19 characters (YYYY-MM-DD HH:MM:SS)
ALTER TABLE article MODIFY COLUMN pub_date_temp DATE;
ALTER TABLE article DROP COLUMN pub_date;
ALTER TABLE article CHANGE COLUMN pub_date_temp pub_date DATE;

-- Create Keywords
CREATE TABLE article_keyword (article_id varchar(255), keyword_id INT, PRIMARY KEY (article_id, keyword_id), FOREIGN KEY (article_id) REFERENCES article(_id), FOREIGN KEY(keyword_id) REFERENCES keywords(keyword_id));

– mysql --local-infile=1 --execute="LOAD DATA LOCAL INFILE '~/Downloads/keywords.csv' INTO TABLE keywords FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '\"' IGNORE 1 LINES (keyword_id,keyword_name,keyword_value,keyword_rank,major,article_id); SHOW WARNINGS" -u root -p nyt1

-- Remove unsupported trailing charencter
UPDATE keywords SET article_id = LEFT(article_id, LENGTH(article_id) - 1);

-- Populate the article_keyword links
INSERT INTO article_keyword (keyword_id, article_id)  SELECT DISTINCT keywords.keyword_id, article._id  FROM article INNER JOIN keywords ON article._id = keywords.article_id;

—- Make _id PK
ALTER TABLE article DROP PRIMARY KEY;
ALTER TABLE article ADD PRIMARY KEY (_id);

